### ISSUE TITLE
Create API UI

### ISSUE THREAD

**Issue by Mgranfie** [Apicurio/apicurio-ux-design#22]
Refine and standardize the current workflow and user interface of the create and edit API experience.

[Prototype here](https://redhat.invisionapp.com/share/J7LG0WYWZNF#/298103125_A_Create_Api_Workflow_00b)

**Comment by Mgranfie** [comment]
@EricWittmann just noticed in studio.apicur.io that the create API UI is not implemented as neither a fa full inset or dialog. Other elements in the application that are created use a dialog. This UI uses the breadcrumbs as a destination rather than the dialog pattern for creation. Not sure if I am seeing the most recent implementation of this?  Thought I would ask. It was unexpected to move from the API tab/area when I hit create from the dashboard and there was no cancel, other than to use the back button and it was not clear what would happen. I feel like we talked about this a while back about not having this as two separate steps, but can't recall what we decided on the pattern to house it. Apologies if I am rehashing this... just want to understand before I move it out of the not implemented phase...

Current UI:
![Screen Shot 2019-03-19 at 3 51 40 PM](https://user-images.githubusercontent.com/18149547/54637558-47e43f00-4a5f-11e9-8cdd-25a1ca7a33c6.png)

Dialog UI:
![a_create_api_dialog](https://user-images.githubusercontent.com/18149547/54637575-50d51080-4a5f-11e9-9809-603215b158ae.png)

Let me know what you think... Thanks!

**Comment by EricWittmann** [comment]
This was redesigned but not yet implemented.  It's still on the to-do list.

**Comment by Mgranfie** [comment]
Ah Ok I thought we had talked about it. I will mark my story accordingly,
thanks!

**Comment by Mgranfie** [comment]
Design final. Implementation to do.
