### ISSUE TITLE
Error Messaging Dialogs Review

### ISSUE THREAD

**Issue by Mgranfie** [Apicurio/apicurio-ux-design#24]
The dialogs that currently handle error conditions have some inconsistencies in display and verbiage. There is a range of visual and functional approaches to the presentation.

[Message Mockups Here](https://redhat.invisionapp.com/share/X2M41MT48ER#/305705777_Intro_Messages)

1. Explore ways to present the messaging consistently.
2. Explore text revisions that for clarity and consistency.
3. Create mock ups of revisions for the message identified as needing revisions.
4. Review with Eric to finalize.

**Comment by Mgranfie** [comment]
PatternFly Designs for Log in Page, Guidelines and Code can be found [here](http://www.patternfly.org/pattern-library/application-framework/login-page/#design).

**Comment by EricWittmann** [comment]
Yeah that's the updated login design.  The version of Keycloak we're using now implemented the older PF spec for login.

An upgraded KC might implement the newer model.

**Comment by Mgranfie** [comment]
Ah OK good to know! Thanks.

**Comment by Mgranfie** [comment]
@EricWittmann Have reviewed and posted the updates for the Errors dialogs [here](https://redhat.invisionapp.com/share/Z8M41MVHFSR#/305705777_Intro_Messages).

**Comment by Mgranfie** [comment]
@EricWittmann Graphic for the "Something went wrong" message can be found [here](https://drive.google.com/file/d/1gtzug1oDnGXQJrvCE0m9yrENNaRXiUWB/view?usp=sharing).

**Comment by Mgranfie** [comment]
@EricWittmann Providing a reference to visual guidelines from PatterFly, that we can use on the full screen message/page, found [here](http://www.patternfly.org/pattern-library/communication/empty-state/).
