### ISSUE TITLE
Define New Data Type - Checkboxes should be squares

### ISSUE THREAD

**Issue by Mgranfie** [Apicurio/apicurio-ux-design#39]
The circle check does not imply checkbox behavior and could easily be considered option buttons. These also do not align to PatternFly card UI Standards.
![screen shot 2018-10-23 at 11 48 36 am](https://user-images.githubusercontent.com/18149547/47373547-1175e400-d6ba-11e8-862d-39cf886ed94f.png)

**Comment by EricWittmann** [comment]
Those cards are radio buttons (mutually exclusive options).  I think the circles are correct.

**Comment by Mgranfie** [comment]
@EricWittmann oh right... Ok can we use the option buttons here to support the mutual exclusivity  :)

**Comment by EricWittmann** [comment]
Oh right - I forgot to change that icon from "fa-check-circle-o" to "fa-dot-circle-o".  I've done that now so it'll be correct in the next version of Apicurio.

**Comment by EricWittmann** [comment]
Looks like this now:

![image](https://user-images.githubusercontent.com/1890703/47435704-282c4180-d773-11e8-96ea-b6c6b5b83315.png)

**Comment by Mgranfie** [comment]
Awesome!!
